.github/workflows/ci-sonar.yml
.github/workflows/ci.yml
CMakeLists.txt
sonar-project.properties

N/A
Feature
There is no continuous integration
Continuous integration uses Github Actions

Setup CI using Github Actions

---

.github/workflows/ci.yml
CMakeLists.txt

N/A
Feature
CI is done only on ubuntu
CI is done on ubuntu and macos

Activate CI on macos

---

src/iidm/ValidationUtils.cpp
test/iidm/CurrentLimitsTest.cpp

N/A
Bug fix
An exception is thrown when the permanent limit is not set. 
No exception is thrown when the permanent limit is not set, as in the java version.
(if any of the …

Fix assertions on current limits

---

CMakeLists.txt
include/powsybl/iidm/ExtensionProviders.hpp
include/powsybl/iidm/ExtensionProviders.hxx
src/CMakeLists.txt
src/test/CMakeLists.txt
src/test/ExtensionFixture.cpp

Signed-off-by: Sébastien LAIGRE <sebastien.laigre@rte-france.com>

Use std::regex instead of boost::regex

---

src/iidm/NodeBreakerVoltageLevelTopology.cpp
test/iidm/NodeBreakerVoltageLevelTest.cpp

Fix NodeBreakerVoltageLevel::CalculatedBusTopology::getConnectableBus

---

include/powsybl/iidm/StaticVarCompensator.hpp
include/powsybl/iidm/StaticVarCompensatorAdder.hpp
src/iidm/StaticVarCompensator.cpp
src/iidm/StaticVarCompensatorAdder.cpp
src/iidm/converter/xml/NetworkXml.cpp
src/iidm/converter/xml/StaticVarCompensatorXml.cpp
src/iidm/converter/xml/StaticVarCompensatorXml.hpp
test/iidm/StaticVarCompensatorTest.cpp
test/iidm/converter/xml/StaticVarCompensatorRoundTripTest.cpp
test/resources/V1_0/faultyRegulatingStaticVarCompensatorRoundTripRef.xml
test/resources/V1_1/regulatingStaticVarCompensatorRoundTripRef.xml
test/resources/V1_1/staticVarCompensatorRoundTripRef.xml

Backport for Java PR #1072 https://github.com/powsybl/powsybl-core/pull/1072/
Add Regulating terminal for SVC. Update in XML serialization.
(if any of the questions/checkboxes …

Regulating terminal for svc

---

include/powsybl/iidm/Generator.hpp
include/powsybl/stdcxx/reference_wrapper.hpp
src/iidm/Generator.cpp
src/iidm/GeneratorAdder.cpp
src/iidm/converter/xml/GeneratorXml.cpp
test/iidm/GeneratorTest.cpp
test/network/EurostagFactoryTest.cpp

Update Regulating terminal of Generator API

---

doxygen/Doxyfile.in
examples/example1/CMakeLists.txt
examples/example1/example1.cpp
examples/example1/main.cpp
examples/example2/CMakeLists.txt

N/A
Docs
There is no example section in the doxygen
The section has been added. To avoid multiple main.cpp in the example index, the `example1/main.cpp` file has been renamed to `example1/example1.cpp`. …

Add examples in the doxygen

---

src/iidm/CalculatedBus.cpp

Fix issue #33 
(https://github.com/powsybl/powsybl-core/pull/1147/files)
Issue #33 

Fix CalculatedBus::findTerminal (#33)

---

README.md
doxygen/Doxyfile.in

N/A
Doc
There is an extra "Build from sources" title in the requirements section of the README.md
This title has been removed
(if any of the questions/checkboxes don't apply, …

Fix README.md

---

extensions/entsoe/CMakeLists.txt
extensions/entsoe/include/powsybl/iidm/extensions/entsoe/XnodeAdder.hpp
extensions/entsoe/src/XnodeAdder.cpp
extensions/entsoe/src/XnodeXmlSerializer.cpp
extensions/entsoe/test/XnodeTest.cpp

Add XnodeAdder and use it from xml serializer

---

extensions/iidm/CMakeLists.txt
extensions/iidm/include/powsybl/iidm/extensions/iidm/ActivePowerControlAdder.hpp
extensions/iidm/src/ActivePowerControlAdder.cpp
extensions/iidm/src/ActivePowerControlXmlSerializer.cpp
extensions/iidm/test/ActivePowerControlTest.cpp

Add ActivePowerControlAdder and use it from xml serializer

---

include/powsybl/iidm/VoltageLevel.hpp
include/powsybl/iidm/VoltageLevelViews.hpp
include/powsybl/iidm/converter/xml/IidmXmlUtil.hpp
include/powsybl/math/UndirectedGraph.hpp
include/powsybl/math/UndirectedGraph.hxx
src/iidm/BusBreakerVoltageLevel.cpp
src/iidm/BusBreakerVoltageLevel.hpp
src/iidm/Connectable.cpp
src/iidm/NodeBreakerVoltageLevel.cpp
src/iidm/NodeBreakerVoltageLevel.hpp
src/iidm/NodeBreakerVoltageLevelViews.cpp
src/iidm/NodeBreakerVoltageLevelViews.hpp
src/iidm/converter/xml/IidmXmlUtil.cpp
src/iidm/converter/xml/VoltageLevelXml.cpp
test/iidm/GeneratorTest.cpp
test/iidm/NetworkFactory.cpp
test/iidm/NetworkTest.cpp
test/iidm/NodeBreakerVoltageLevelTest.cpp
test/math/UndirectedGraphTest.cpp
test/resources/V1_2/LccRoundTripRef.xml
test/resources/V1_2/VscRoundTripRef.xml
test/resources/V1_2/fictitiousSwitchRef.xml
test/resources/V1_2/internalConnections.xml

[IIDM v1.2] Update node creation mechanism

---

include/powsybl/iidm/ValidationUtils.hpp
src/iidm/HvdcLine.cpp
src/iidm/HvdcLineAdder.cpp
src/iidm/ValidationUtils.cpp
test/iidm/HvdcLineTest.cpp
test/iidm/LccConverterStationTest.cpp
test/iidm/NetworkFactory.cpp
test/iidm/VscConverterStationTest.cpp
test/resources/V1_0/LccRoundTripRef.xml
test/resources/V1_0/VscRoundTripRef.xml
test/resources/V1_1/LccRoundTripRef.xml
test/resources/V1_1/VscRoundTripRef.xml
test/resources/V1_2/LccRoundTripRef.xml
test/resources/V1_2/VscRoundTripRef.xml

[IIDM v1.2] Add checks for HVDC lines (power factor and loss factor) (#127 and #128)

---

extensions/iidm/CMakeLists.txt
extensions/iidm/include/powsybl/iidm/extensions/iidm/CoordinatedReactiveControlAdder.hpp
extensions/iidm/src/CoordinatedReactiveControlAdder.cpp
extensions/iidm/src/CoordinatedReactiveControlXmlSerializer.cpp
extensions/iidm/test/CoordinatedReactiveControlTest.cpp

Bacport of https://github.com/powsybl/powsybl-core/pull/1255
#120 

[IIDM v1.2] Use new extension API for CoordinatedReactiveControl (#120)

---

include/powsybl/iidm/VoltageLevelViews.hpp
include/powsybl/math/UndirectedGraph.hpp
include/powsybl/math/UndirectedGraph.hxx
src/iidm/NodeBreakerVoltageLevelViews.cpp
src/iidm/NodeBreakerVoltageLevelViews.hpp
test/iidm/NodeBreakerVoltageLevelTest.cpp
test/math/UndirectedGraphTest.cpp

[IIDM V1.2] Add a convenient function to get a Terminal from its node (#67+#75)

---

extensions/iidm/CMakeLists.txt
extensions/iidm/include/powsybl/iidm/extensions/iidm/TwoWindingsTransformerPhaseAngleClockAdder.hpp
extensions/iidm/src/TwoWindingsTransformerPhaseAngleClock.cpp
extensions/iidm/src/TwoWindingsTransformerPhaseAngleClockAdder.cpp
extensions/iidm/src/TwoWindingsTransformerPhaseAngleClockXmlSerializer.cpp
extensions/iidm/test/TwoWindingsTransformerPhaseAngleClockTest.cpp

Backport of https://github.com/powsybl/powsybl-core/pull/1272
#120  …

[IIDM v1.2] Use new extension API for TwoWindingsTransformerPhaseAngleClock (#120)

---

extensions/iidm/CMakeLists.txt
extensions/iidm/include/powsybl/iidm/extensions/iidm/ThreeWindingsTransformerPhaseAngleClockAdder.hpp
extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClock.cpp
extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClockAdder.cpp
extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.cpp
extensions/iidm/test/ThreeWindingsTransformerPhaseAngleClockTest.cpp

Backport of https://github.com/powsybl/powsybl-core/pull/1336
#120  …

[IIDM v1.2] Use new extension api for ThreeWindingsTransformerPhaseAngleClock extension (#120)

---

extensions/entsoe/CMakeLists.txt
extensions/entsoe/include/powsybl/iidm/extensions/entsoe/EntsoeAreaAdder.hpp
extensions/entsoe/src/EntsoeAreaAdder.cpp
extensions/entsoe/src/EntsoeAreaXmlSerializer.cpp
extensions/entsoe/test/EntsoeAreaTest.cpp

Backport of https://github.com/powsybl/powsybl-core/pull/1342
#120  …

[IIDM v1.2] Use new extension api for EntsoeArea (#120) 

---

extensions/entsoe/CMakeLists.txt
extensions/entsoe/include/powsybl/iidm/extensions/entsoe/MergedXnodeAdder.hpp
extensions/entsoe/src/MergedXnode.cpp
extensions/entsoe/src/MergedXnodeAdder.cpp
extensions/entsoe/src/MergedXnodeXmlSerializer.cpp
extensions/entsoe/test/MergedXnodeTest.cpp

Backport of https://github.com/powsybl/powsybl-core/pull/1343
#120 

[IIDM v1.2] Use new extension api for MergedXnode (#120) 

---

.github/workflows/ci.yml

N/A
Update the JDK version used to run sonar. Since several weeks, sonar reports that the support of java 8 will end in october. Upgrading to Java 11 will make sonar continue to work
After sonar analysis, there is a warning message on the PR conversation page to warn that old version of java is used
**What is the new behavior (if this is a feature …

Sonar java11

---

extensions/iidm/CMakeLists.txt
extensions/iidm/include/powsybl/iidm/extensions/iidm/LoadDetail.hpp
extensions/iidm/include/powsybl/iidm/extensions/iidm/LoadDetailAdder.hpp
extensions/iidm/include/powsybl/iidm/extensions/iidm/LoadDetailXmlSerializer.hpp
extensions/iidm/resources/loadDetailOldRef.xml
extensions/iidm/resources/loadDetailRef.xml
extensions/iidm/src/Iidm.cpp
extensions/iidm/src/LoadDetail.cpp
extensions/iidm/src/LoadDetailAdder.cpp
extensions/iidm/src/LoadDetailXmlSerializer.cpp
extensions/iidm/test/LoadDetailTest.cpp

[IIDM v1.3] Add LoadDetail extension (#157)

---

extensions/iidm/resources/voltagePerReactivePowerControl.xml
src/iidm/converter/xml/StaticVarCompensatorXml.cpp
test/resources/V1_3/regulatingStaticVarCompensatorRoundTripRef.xml
test/resources/V1_3/staticVarCompensatorRoundTripRef.xml

[IIDM v1.3] Rename to setpoint (#162)

---

include/powsybl/iidm/Connectable.hpp
include/powsybl/iidm/HvdcLine.hpp
include/powsybl/iidm/Identifiable.hpp
include/powsybl/iidm/MultiVariantObject.hpp
include/powsybl/iidm/Switch.hpp
include/powsybl/iidm/VoltageLevel.hpp
src/iidm/BusBreakerVoltageLevel.cpp
src/iidm/ConfiguredBus.cpp
src/iidm/ConfiguredBus.hpp
src/iidm/Connectable.cpp
src/iidm/HvdcLine.cpp
src/iidm/Identifiable.cpp
src/iidm/NodeBreakerVoltageLevel.cpp
src/iidm/Switch.cpp
test/iidm/NetworkIndexTest.cpp

#165 
Bug fix/Feature
This PR fixes #165 
It also backports https://github.com/powsybl/powsybl-core/pull/682 and https://github.com/powsybl/powsybl-core/pull/1476
(if any of the …

[IIDM v1.3] Bug MultiVariant (#165)

---

src/iidm/AbstractMultiVariantConnectableExtension.cpp
src/iidm/ThreeWindingsTransformer.cpp
src/iidm/converter/xml/AbstractTransformerXml.hxx
src/iidm/converter/xml/GeneratorXml.cpp
src/iidm/converter/xml/StaticVarCompensatorXml.cpp

[IIDM v1.3] Use network accessor from connectable when it is possible (#161)

---

include/powsybl/iidm/Extension.hpp

[IIDM v1.3] Extensions non copiable

---

include/powsybl/iidm/AbstractMultiVariantIdentifiableExtension.hpp
include/powsybl/iidm/extensions/SlackTerminal.hpp
include/powsybl/iidm/extensions/SlackTerminalAdder.hpp
include/powsybl/iidm/util/TerminalFinder.hpp
include/powsybl/network/FictitiousSwitchFactory.hpp
include/powsybl/stdcxx/instanceof.hpp
src/CMakeLists.txt
src/iidm/extensions/LoadDetail.cpp
src/iidm/extensions/SlackTerminal.cpp
src/iidm/extensions/SlackTerminalAdder.cpp
src/iidm/util/TerminalFinder.cpp
src/network/FictitiousSwitchFactory.cpp
test/iidm/CMakeLists.txt
test/iidm/extensions/SlackTerminalTest.cpp
test/iidm/util/TerminalFinderTest.cpp

[IIDM v1.3] Add SlackTerminal extension

---

include/powsybl/iidm/Network.hpp
include/powsybl/iidm/NetworkVariant.hpp
include/powsybl/iidm/Variant.hpp
include/powsybl/iidm/Variant.hxx
include/powsybl/iidm/VariantArray.hpp
include/powsybl/iidm/VariantArray.hxx
src/iidm/BusBreakerVoltageLevel.cpp
src/iidm/BusBreakerVoltageLevel.hpp
src/iidm/BusBreakerVoltageLevelVariant.cpp
src/iidm/BusBreakerVoltageLevelVariant.hpp
src/iidm/Network.cpp
src/iidm/NetworkVariant.cpp
src/iidm/NodeBreakerVoltageLevel.cpp
src/iidm/NodeBreakerVoltageLevel.hpp
src/iidm/NodeBreakerVoltageLevelVariant.cpp
src/iidm/NodeBreakerVoltageLevelVariant.hpp

N/A
Refactoring
The current implementation of Variant and VariantArray are not ready to be moveable, specially for the network's variant
Add the owner in the Variant and the VariantArray, and refactor the variants of the voltage levels and the network
**Does this PR introduce a breaking change or …

Refactor variants

---

extensions/sld/CMakeLists.txt
extensions/sld/include/powsybl/iidm/extensions/sld/ConnectablePosition.hpp
extensions/sld/include/powsybl/iidm/extensions/sld/ConnectablePositionAdder.hpp
extensions/sld/include/powsybl/iidm/extensions/sld/ConnectablePositionXmlSerializer.hpp
extensions/sld/resources/connectablePositionFeeder0.xml
extensions/sld/resources/connectablePositionFeeders123.xml
extensions/sld/src/ConnectablePosition.cpp
extensions/sld/src/ConnectablePositionAdder.cpp
extensions/sld/src/ConnectablePositionXmlSerializer.cpp
extensions/sld/src/Sld.cpp
extensions/sld/test/ConnectablePositionTest.cpp

[IIDM v1.3] Add ConnectablePosition extension (#191)

---

include/powsybl/iidm/CurrentLimits.hpp
src/CMakeLists.txt
src/iidm/NodeBreakerVoltageLevelTopology.hpp

Signed-off-by: Gautier Bureau <gautier.bureau@gmail.com>
It fixes compilation for VS2015
Compilation fails
Compilation is ok

Fix compilation with VS2015 on Windows.

---

src/iidm/ThreeWindingsTransformerLegAdder.cpp
test/iidm/ThreeWindingsTransformerTest.cpp

**Should be merged in branch `integration/v1.4.0`**
#237

[IIDM v1.4] Add Substation in error message (#237)

---

src/iidm/converter/xml/NetworkXml.cpp

**This branch should be merged in integration/v1.4.0**
#239 

[IIDM v1.4] Make sure XML serializer is valid (#239)

---

src/iidm/NodeBreakerVoltageLevel.cpp

**Should be merged in integration/v1.4.0**
#242

[IIDM v1.4] Invalidate cache nbkvl (#242)

---

include/powsybl/iidm/Identifiable.hpp
include/powsybl/iidm/converter/Constants.hpp
src/iidm/Identifiable.cpp
src/iidm/converter/xml/AliasesXml.cpp
src/iidm/converter/xml/ShuntCompensatorXml.cpp
test/iidm/AliasesTest.cpp

[IIDM v1.4] Aliases by type (#243)

---

CMakeLists.txt
README.md
extensions/entsoe/CMakeLists.txt
extensions/iidm/CMakeLists.txt
extensions/sld/CMakeLists.txt
src/CMakeLists.txt

Add option to disable unit tests build (#184)

---

include/powsybl/iidm/ExtensionProviders.hpp
include/powsybl/iidm/PhaseTapChangerHolder.hpp
include/powsybl/iidm/RatioTapChangerHolder.hpp
include/powsybl/iidm/ThreeWindingsTransformerLeg.hpp
include/powsybl/iidm/TwoWindingsTransformer.hpp
src/iidm/ExtensionProviders.cpp
src/iidm/ThreeWindingsTransformerLeg.cpp
src/iidm/TwoWindingsTransformer.cpp

Pass unique_ptr as parameters by rvalue (#234)

---

include/powsybl/iidm/converter/Anonymizer.hpp
include/powsybl/iidm/converter/FakeAnonymizer.hpp
include/powsybl/iidm/converter/SimpleAnonymizer.hpp
include/powsybl/iidm/converter/xml/NetworkXmlReaderContext.hpp
include/powsybl/iidm/converter/xml/NetworkXmlWriterContext.hpp
src/CMakeLists.txt
src/iidm/Network.cpp
src/iidm/converter/FakeAnonymizer.cpp
src/iidm/converter/SimpleAnonymizer.cpp
src/iidm/converter/xml/AbstractConnectableXml.hxx
src/iidm/converter/xml/NetworkXml.cpp
src/iidm/converter/xml/NetworkXml.hpp
src/iidm/converter/xml/NetworkXmlReaderContext.cpp
src/iidm/converter/xml/NetworkXmlWriterContext.cpp
src/iidm/converter/xml/SubstationXml.cpp
test/iidm/CMakeLists.txt
test/iidm/converter/SimpleAnonymizerTest.cpp
test/iidm/converter/xml/IidmXmlUtilTest.cpp
test/iidm/converter/xml/NetworkXmlReaderContextTest.cpp
test/iidm/converter/xml/NetworkXmlWriterContextTest.cpp

#71
This PR adds `SimpleAnonymizer` class. By using this new class and really anonymizing a network, 2 bugs were found in anonymization/deanonymization of network. Both are fixed in this PR by 2 separated commits : 
- 7761f81161f9a24299a46ecb7c449bf7dacb3fa3
- 6fb642f19c7d18727a473d9b99d9a1dbf56cbc46
**What is the new behavior (if this is a feature …

[IIDM v1.4] Add SimpleAnonymizer (#71)

---

src/iidm/NodeBreakerVoltageLevel.cpp
test/iidm/NodeBreakerVoltageLevelTest.cpp

Signed-off-by: Luma <zamarrenolm@aia.es>
solves issue #280

fix node/breaker voltage level connect/disconnect for internal connections

---

include/powsybl/iidm/converter/xml/CurrentLimitsXml.hxx
include/powsybl/network/FourSubstationsNodeBreakerFactory.hpp
src/CMakeLists.txt
src/iidm/converter/xml/CurrentLimitsXml.cpp
src/network/FourSubstationsNodeBreakerFactory.cpp
test/iidm/converter/xml/CMakeLists.txt
test/iidm/converter/xml/FourSubstationsNodeBreakerTest.cpp
test/resources/V1_4/fourSubstationsNbk.xml

Add four substations node breaker factory (#276)

---

include/powsybl/iidm/converter/ExportOptions.hpp
include/powsybl/iidm/converter/xml/IidmXmlUtil.hpp
src/iidm/converter/ExportOptions.cpp
src/iidm/converter/xml/IidmXmlUtil.cpp

No
Cosmetic
Some functions in `ExportOptions` and `IidmXmlUtil` are not alphabetically well placed.
Those functions in `ExportOptions` and `IidmXmlUtil` are well placed.
(if any …

Cosmetic: fix methods order

---

CMakeLists.txt
README.md

Signed-off-by: Gautier Bureau <gautier.bureau@gmail.com>
#296 
Feature
#296
#296

Add option to disable tools build.

---

include/powsybl/iidm/Connectable.hpp
include/powsybl/iidm/HvdcConverterStation.hpp
include/powsybl/iidm/Network.hpp
include/powsybl/iidm/Substation.hpp
include/powsybl/iidm/VoltageLevel.hpp
include/powsybl/iidm/util/Substations.hpp
include/powsybl/iidm/util/VoltageLevels.hpp
src/CMakeLists.txt
src/iidm/BusBreakerVoltageLevel.cpp
src/iidm/BusBreakerVoltageLevel.hpp
src/iidm/HvdcConverterStation.cpp
src/iidm/Network.cpp
src/iidm/NodeBreakerVoltageLevel.cpp
src/iidm/NodeBreakerVoltageLevel.hpp
src/iidm/Substation.cpp
src/iidm/VoltageLevel.cpp
src/iidm/util/Substations.cpp
src/iidm/util/VoltageLevels.cpp
test/iidm/HvdcLineTest.cpp
test/iidm/SubstationTest.cpp

**This PR should be rebased once #286 has been merged.**
No
Add missing `Substation::remove()` method
Method is missing => N/A
Method is available
(if any of the …

Add Substation::remove()

---

extensions/entsoe/CMakeLists.txt
extensions/iidm/CMakeLists.txt
extensions/sld/CMakeLists.txt

N/A
Arguable
The extensions static libraries are linked with the dynamic version of the IIDM library
The extensions static libraries are linked with the static version of the IIDM library
**Other …

Fix iidm static

---

src/iidm/BusBreakerVoltageLevel.cpp
test/iidm/TerminalTest.cpp

N/A
Bug fix
powsybl-iidm4cpp v1.4.0-RC1 is not compatible with CentOS 7
This PR aims to fix the compilations issues we encounter with CentOS 7
(if any of the questions/checkboxes …

Fix compilation centos

---

include/powsybl/iidm/Country.hpp

#309 
Cosmetic bug
There is a typo in the copyright information of Country.hpp
The typo has been fixed
(if any of the questions/checkboxes don't apply, please delete them …

Fix copyright header in Country.hpp

---

src/iidm/ExtensionProviders.cpp
test/iidm/converter/xml/CMakeLists.txt
test/iidm/converter/xml/ExtensionProvidersTest.cpp

Fix bad string format in error message (#313)

---

.github/workflows/ci.yml
.github/workflows/clang-tidy.yml
doxygen/Doxyfile.in
doxygen/cppreference-doxygen-web.tag.xml
doxygen/powsybl.svg
examples/example1/eurostag-tutorial1.xml

The following files still does not have any licence header:
powsybl-iidm4cpp/README.md
powsybl-iidm4cpp/examples/example2/README.md
powsybl-iidm4cpp/examples/README.md
powsybl-iidm4cpp/examples/example1/README.md
powsybl-iidm4cpp/examples/example1/eurostag-tutorial1.xml
powsybl-iidm4cpp/examples/example3/README.md
powsybl-iidm4cpp/doxygen/Doxyfile.in
powsybl-iidm4cpp/doxygen/cppreference-doxygen-web.tag.xml
powsybl-iidm4cpp/doxygen/powsybl.svg
But I think it's not relevant (to be discussed)
#321
**What kind of change …

Fix missing licence header (#321)

---

src/iidm/converter/xml/NetworkXml.cpp

[IIDM v1.5.1] Throw a warning instead of error log when extensions have not been found (#328)

---

extensions/iidm/CMakeLists.txt
extensions/iidm/include/powsybl/iidm/extensions/iidm/HvdcAngleDroopActivePowerControl.hpp
extensions/iidm/include/powsybl/iidm/extensions/iidm/HvdcAngleDroopActivePowerControlAdder.hpp
extensions/iidm/include/powsybl/iidm/extensions/iidm/HvdcAngleDroopActivePowerControlXmlSerializer.hpp
extensions/iidm/include/powsybl/iidm/extensions/iidm/HvdcOperatorActivePowerRange.hpp
extensions/iidm/include/powsybl/iidm/extensions/iidm/HvdcOperatorActivePowerRangeAdder.hpp
extensions/iidm/include/powsybl/iidm/extensions/iidm/HvdcOperatorActivePowerRangeXmlSerializer.hpp
extensions/iidm/resources/LccRoundTripRef.xml
extensions/iidm/resources/VscRoundTripRef.xml
extensions/iidm/resources/hvdcAngleDroopActivePowerControl.xml
extensions/iidm/resources/hvdcOperatorActivePowerRange.xml
extensions/iidm/src/HvdcAngleDroopActivePowerControl.cpp
extensions/iidm/src/HvdcAngleDroopActivePowerControlAdder.cpp
extensions/iidm/src/HvdcAngleDroopActivePowerControlXmlSerializer.cpp
extensions/iidm/src/HvdcOperatorActivePowerRange.cpp
extensions/iidm/src/HvdcOperatorActivePowerRangeAdder.cpp
extensions/iidm/src/HvdcOperatorActivePowerRangeXmlSerializer.cpp
extensions/iidm/src/Iidm.cpp
extensions/iidm/test/HvdcAngleDroopActivePowerControlTest.cpp
extensions/iidm/test/HvdcOperatorActivePowerRangeTest.cpp

[IIDM v1.5.1] Add new iidm hvdc extensions (#327)

---

include/powsybl/iidm/Network.hpp
src/iidm/BusBreakerVoltageLevelViews.cpp

Optimise getBus in Bus/Breaker view for default Network implementation (#332)

---

include/powsybl/iidm/NetworkViews.hpp
src/iidm/NetworkViews.cpp
test/iidm/ComponentsTest.cpp

Add BusView::getSynchronousComponents() (#337)

---

include/powsybl/iidm/BusRef.hpp
include/powsybl/iidm/IdBasedBusRef.hpp
src/CMakeLists.txt
src/iidm/BusRef.cpp
src/iidm/IdBasedBusRef.cpp
test/iidm/CMakeLists.txt
test/iidm/IdBasedBusRefTest.cpp

Add BusRef and IdBasedBusRef (#334)

---

test/iidm/NodeBreakerVoltageLevelTest.cpp

Add non-reg test for potential issue (#381)

---

extensions/sld/CMakeLists.txt
extensions/sld/include/powsybl/iidm/extensions/sld/BranchStatus.hpp
extensions/sld/include/powsybl/iidm/extensions/sld/BranchStatusAdder.hpp
extensions/sld/include/powsybl/iidm/extensions/sld/BranchStatusXmlSerializer.hpp
extensions/sld/resources/branchStatusRef.xml
extensions/sld/src/BranchStatus.cpp
extensions/sld/src/BranchStatusAdder.cpp
extensions/sld/src/BranchStatusXmlSerializer.cpp
extensions/sld/src/Sld.cpp
extensions/sld/test/BranchStatusTest.cpp

Add BranchStatus extension (#390)

---

src/iidm/IdBasedBusRef.cpp

No
Smell fix
Behaviour is ok but sonar highlight a too complex structure smell here : https://sonarcloud.io/project/issues?id=com.powsybl%3Apowsybl-iidm4cpp&pullRequest=405&resolved=false&severities=CRITICAL&types=CODE_SMELL
The smell is fixed.
**Does this PR introduce a breaking change or …

Fix critical smell introduced in integration/v1.5.0

---

include/powsybl/iidm/util/AbstractHalfLineBoundary.hpp
include/powsybl/iidm/util/DanglingLineBoundary.hpp
src/CMakeLists.txt
src/iidm/DanglingLine.cpp
src/iidm/HalfLineBoundary.cpp
src/iidm/HalfLineBoundary.hpp
src/iidm/util/AbstractHalfLineBoundary.cpp
src/iidm/util/DanglingLineBoundary.cpp

[IIDM v1.6.0] Move Boundary classes formulas as util (#364)

---

.github/workflows/ci.yml

N/A
CI
Recently, the `windows-latest` workflows change from Windows Server 2019 to Windows Server 2022. The Visual Studio version declared in the CI script doesn't exist anymore and has to be updated.
The CI under windows works
**Does this PR introduce a breaking change or deprecate an API?** *If …

Update Visual Studio version

---

include/powsybl/iidm/VscConverterStation.hpp
include/powsybl/iidm/VscConverterStationAdder.hpp
src/iidm/VscConverterStation.cpp
src/iidm/VscConverterStationAdder.cpp
src/iidm/converter/xml/VscConverterStationXml.cpp
test/iidm/VscConverterStationTest.cpp
test/resources/V1_6/VscRoundTripRef.xml

Add regulating terminal for vsc converter station (#392)

---

extensions/iidm/CMakeLists.txt
extensions/iidm/include/powsybl/iidm/extensions/iidm/BranchObservability.hpp
extensions/iidm/include/powsybl/iidm/extensions/iidm/BranchObservabilityAdder.hpp
extensions/iidm/include/powsybl/iidm/extensions/iidm/BranchObservabilityXmlSerializer.hpp
extensions/iidm/include/powsybl/iidm/extensions/iidm/Constants.hpp
extensions/iidm/resources/branchObservabilityRoundTripRef.xml
extensions/iidm/resources/branchObservabilityRoundTripRefInvalid.xml
extensions/iidm/src/BranchObservability.cpp
extensions/iidm/src/BranchObservabilityAdder.cpp
extensions/iidm/src/BranchObservabilityXmlSerializer.cpp
extensions/iidm/src/Iidm.cpp
extensions/iidm/test/BranchObservabilityTest.cpp

Add BranchObservability extension (#393)

---

.github/workflows/ci.yml

No
Bug fix
Sonar report is broken because of code coverage reporting (gcovr has been updated to v5.1 in pip repository, and this version has an identified bug here https://github.com/gcovr/gcovr/issues/590)
Sonar report is ok. We use gcovr from ubuntu repository instead of pip.
**Does this PR …

Fix sonar report in QA (due to gcovr)

---

extensions/entsoe/include/powsybl/iidm/extensions/entsoe/MergedXnodeXmlSerializer.hpp
extensions/entsoe/resources/mergedXnode.xml
extensions/entsoe/src/MergedXnodeXmlSerializer.cpp
extensions/entsoe/test/MergedXnodeTest.cpp
include/powsybl/iidm/converter/xml/AbstractVersionableExtensionXmlSerializer.hpp
include/powsybl/iidm/converter/xml/ExtensionXmlSerializer.hpp
include/powsybl/iidm/converter/xml/NetworkXmlReaderContext.hpp
src/iidm/converter/xml/AbstractVersionableExtensionXmlSerializer.cpp
src/iidm/converter/xml/ExtensionXmlSerializer.cpp
src/iidm/converter/xml/NetworkXmlReaderContext.cpp

Add line1Name and line2Name to mergedXNode xml (#378)

---

extensions/iidm/include/powsybl/iidm/extensions/iidm/HvdcAngleDroopActivePowerControlAdder.hpp

No
Fix documentation
Documentation suffers from copy/paste error
Documentation is ok

Fix documentation of HvdcAngleDroopActivePowerControlAdder::createExtension

---

src/iidm/extensions/SlackTerminalXmlSerializer.cpp

Signed-off-by: Gautier Bureau <gautier.bureau@rte-france.com>

Fix SlackTerminal optional side attribute.

---

.clang-tidy
extensions/iidm/resources/disMeasRef.xml
extensions/iidm/resources/measRef.xml
extensions/iidm/src/DiscreteMeasurementsXmlSerializer.cpp
extensions/iidm/src/MeasurementsXmlSerializer.cpp
extensions/iidm/test/DiscreteMeasurementsTest.cpp
extensions/iidm/test/MeasurementsTest.cpp

**Please check if the PR fulfills these requirements**
**Does this PR already have an issue describing the problem?**
Fixes #450 
**What kind of change does this PR introduce?**
Bug fix
**What is the current behavior?**
Id attribute required in measurement/discrete measurement extension
Id attribute option in measurement/discrete measurement extension
**Does this PR introduce a breaking change or deprecate an API?**

Id attribute optional in measurement/discrete measurement extensions
