powsybl/powsybl-iidm4cpp

- CMakeLists.txt
- README.md
- sonar-project.properties
Docs
The project doesn't compile on Ubuntu 18.04 with the default cmake package, because the target `LibXml2::LibXml2` is not created
We change the minimum version to 3.12 in the main CMakeLists.txt, and adapt the documentation.
**Does this PR introduce a breaking change or deprecate an API?** *If …
> Change CMAKE minimum version and update documentation

- CMakeLists.txt
N/A
Bug fix
The minimal version of CMake is v3.12 but before CMake 3.15, the `Boost_VERSION_MACRO` variable is not defined. In that case, depending on the version of boost you use, the BOOST_ARGS_SEPARATOR could have wrong value.
We change the test to support both modern and old FindBoost script. …
> Fix the test to defined the BOOST_ARGS_SEPARATOR variable

- include/powsybl/iidm/Network.hpp
- src/test/converter/RoundTrip.cpp
- tools/benchmark/Benchmark.cpp
N/A
Bug fix?
If you use `Network::writeXml` you have to include Anonymizer.hpp because this method returns a `std::unique_ptr<Anonymizer>`. The forward declaration in Network.hpp is not sufficient here, we have to include the header.
Include the header of Anonymizer is not needed anymore. …
> Network.hpp should include Anonymizer.hpp

- src/iidm/converter/xml/GeneratorXml.cpp
#24 
Feature
The regulating terminal of a generator is exported if it exists and is not connected to a different bus than the local terminal
The regulating terminal of a generator is exported if it's not the local terminal even they are connected to the same bus
**Does this PR introduce a breaking …
> Write the regulatingTerminal of a generator only if its not the local terminal

- src/iidm/RatioTapChanger.cpp
- src/iidm/RatioTapChangerAdder.cpp
- src/iidm/ValidationUtils.cpp
- src/iidm/ValidationUtils.hpp
- test/iidm/RatioTapChangerTest.cpp
> Fix checkRatioTapChangerRegulation

- extensions/iidm/CMakeLists.txt
- extensions/iidm/include/powsybl/iidm/extensions/iidm/ThreeWindingsTransformerPhaseAngleClock.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/TwoWindingsTransformerPhaseAngleClock.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/TwoWindingsTransformerPhaseAngleClockXmlSerializer.hpp
- extensions/iidm/resources/threeWindingsTransformerPhaseAngleClock.xml
- extensions/iidm/resources/twoWindingsTransformerPhaseAngleClock.xml
- extensions/iidm/src/Iidm.cpp
- extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClock.cpp
- extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.cpp
- extensions/iidm/src/TwoWindingsTransformerPhaseAngleClock.cpp
- extensions/iidm/src/TwoWindingsTransformerPhaseAngleClockXmlSerializer.cpp
- extensions/iidm/test/ThreeWindingsTransformerPhaseAngleClockTest.cpp
- extensions/iidm/test/TwoWindingsTransformerPhaseAngleClockTest.cpp
- include/powsybl/network/ThreeWindingsTransformerNetworkFactory.hpp
- include/powsybl/xml/XmlStreamWriter.hpp
- src/CMakeLists.txt
- src/iidm/converter/xml/CurrentLimitsXml.cpp
- src/network/ThreeWindingsTransformerNetworkFactory.cpp
- src/xml/XmlStreamWriter.cpp
#18 
Feature
The phaseAngleClock extension doesn't exist
The phaseAngleClock extension is available for both 2 and 3 windings transformer.
This PR doesn't fix the second part of …
> Implement phaseAngleClock extension for 2 and 3 windings transformers

- src/iidm/converter/xml/VoltageLevelXml.cpp
This PR activates the filtering of buses for the Bus/Branch topology in VL exporter.
Unchanged
The behavior is unchanged because the connected and synchronous component are not implemented yet.
**Other …
> Fix the TODO in VoltageLevelXml for Bus/Branch topology

- include/powsybl/iidm/HvdcConverterStation.hpp
- include/powsybl/iidm/LccConverterStation.hpp
- include/powsybl/iidm/VscConverterStation.hpp
- src/iidm/HvdcConverterStation.cpp
- src/iidm/LccConverterStation.cpp
- src/iidm/VscConverterStation.cpp
N/A
Refactoring
The HvdcConverterStation::setLossFactor method is hidden in the subcalsses.
As the return type is polymorphic, it's possible to override this method by changing the return type.
**Other …
> Refactor to do not hide setLossFactor

- include/powsybl/iidm/BusbarSection.hpp
- src/iidm/BusbarSection.cpp
- src/iidm/BusbarSectionAdder.cpp
N/A
Refactoring
The BusbarSection handles a network reference, whereas it's not the case in Java.
The reference to the network has been removed.
(if any of the …
> Fix BusbarSection implementation to be compliant with Java implementation

- include/powsybl/iidm/Bus.hpp
- include/powsybl/iidm/Connectable.hpp
- include/powsybl/iidm/HvdcLine.hpp
- include/powsybl/iidm/Identifiable.hpp
- include/powsybl/iidm/Network.hpp
- include/powsybl/iidm/Substation.hpp
- include/powsybl/iidm/Switch.hpp
- include/powsybl/iidm/VoltageLevel.hpp
- src/iidm/Bus.cpp
- src/iidm/CalculatedBus.cpp
- src/iidm/CalculatedBus.hpp
- src/iidm/ConfiguredBus.cpp
- src/iidm/ConfiguredBus.hpp
- src/iidm/MergedBus.cpp
- src/iidm/MergedBus.hpp
- src/iidm/Network.cpp
- src/iidm/Switch.cpp
- test/iidm/BusBreakerVoltageLevelTest.cpp
- test/iidm/NetworkTest.cpp
- test/iidm/NodeBreakerVoltageLevelTest.cpp
#51 
Feature
There is no way to get the network instance directly from an identifiable.
The getNetwork() method is added to the identifiable class.
Also fix the inconsistencies in getVoltageLevel() return types.
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the …
> Network identifiable

- extensions/entsoe/CMakeLists.txt
- extensions/iidm/CMakeLists.txt
- test/iidm/CMakeLists.txt
- test/logging/CMakeLists.txt
- test/math/CMakeLists.txt
- test/network/CMakeLists.txt
- test/stdcxx/CMakeLists.txt
- test/xml/CMakeLists.txt
N/A
Bug fix
There is a linkage error under Linux, when the cmake version used is lower than 3.15. Starting from the 3.15, the `Boost::dynamic_linkage` property adds `BOOST_ALL_DYN_LINK` compilation flags for every OS. Before this version, this is done only on Windows.
This is a regression introduced in the PR #42 
**What is the new behavior (if this is a …
> Add BOOST_TEST_DYN_LINK to all unit tests targets

- include/powsybl/iidm/converter/Constants.hpp
- include/powsybl/iidm/converter/xml/CurrentLimitsXml.hpp
- include/powsybl/iidm/converter/xml/IidmXmlVersion.hpp
- src/iidm/converter/xml/AbstractConnectableXml.hpp
- src/iidm/converter/xml/AbstractConnectableXml.hxx
- src/iidm/converter/xml/AbstractIdentifiableXml.hxx
- src/iidm/converter/xml/AbstractTransformerXml.hxx
- src/iidm/converter/xml/CurrentLimitsXml.cpp
- src/iidm/converter/xml/DanglingLineXml.cpp
- src/iidm/converter/xml/IidmXmlVersion.cpp
- src/iidm/converter/xml/LineXml.cpp
- src/iidm/converter/xml/NetworkXml.cpp
- src/iidm/converter/xml/NodeBreakerViewInternalConnectionXml.cpp
- src/iidm/converter/xml/PropertiesXml.cpp
- src/iidm/converter/xml/ReactiveLimitsXml.cpp
- src/iidm/converter/xml/TerminalRefXml.cpp
- src/iidm/converter/xml/ThreeWindingsTransformerXml.cpp
- src/iidm/converter/xml/TieLineXml.cpp
- src/iidm/converter/xml/TwoWindingsTransformerXml.cpp
- src/iidm/converter/xml/VoltageLevelXml.cpp
#29 
https://github.com/powsybl/powsybl-core/pull/1129
Feature
All the XIIDM element are exported using the hard coded `iidm` prefix.
In this version, the XIIDM element are still exported using the `iidm` prefix, but the code is ready to a prefix change. It looks more like the java implementation, …
> Allow to write IIDM-XML files in previous versions

- README.md
N/A
Documentation
There is a mistake in the boost install commands for windows. B2 is not available since bootstrap has not been run.
The commands list is OK
(if any of the …
> Fix boost install commands for windows

- include/powsybl/iidm/Extendable.hpp
- include/powsybl/iidm/Extendable.hxx
- include/powsybl/iidm/ExtensionAdder.hpp
- src/CMakeLists.txt
- src/iidm/ExtensionAdder.cpp
- test/iidm/CMakeLists.txt
- test/iidm/ExtensionAdderTest.cpp
Issue #35 
It provides an API to make easier the addition of an extension to an extendable by using an `ExtensionAdder`.
User has to call 
```
std::unique_ptr<MyExtension> myExtension = stdcxx::make_unique<MyExtension>
myExtendable.addExtension(std::move(myExtension ));
``` 
to add the extension.
**What …
> New extension design

- include/powsybl/iidm/Identifiable.hpp
- include/powsybl/stdcxx/Properties.hpp
- include/powsybl/stdcxx/exception.hpp
- src/CMakeLists.txt
- src/iidm/Identifiable.cpp
- src/iidm/converter/xml/AbstractIdentifiableXml.hxx
- src/stdcxx/Properties.cpp
- src/stdcxx/exception.cpp
- test/iidm/CMakeLists.txt
- test/iidm/NetworkTest.cpp
- test/stdcxx/CMakeLists.txt
- test/stdcxx/PropertiesTest.cpp
No
`Properties` are generic feature so can be moved into namespace `stdcxx` instead of `iidm`
`Properties` are located in `iidm` namespace
`Properties` are located in `stdcxx` namespace
**Other …
> Properties moved from iidm to stdcxx namespace

- include/powsybl/test/AssertionUtils.hpp
N/A
Bug fix
The header `boost/test/floating_point_comparison.hpp` is included in `AssertionUtils.hpp` but is deprecated in recent boost version (> 1.65), so a warning is displayed in the compilation log
Remove this header: seems unused?
**Does this PR introduce a breaking change or deprecate an …
> Remove useless deprecated header

- src/test/converter/RoundTrip.cpp
No
Bug fix
Method `RoundTrip::run` was writing twice the input network, instead of reading the serialized network. So it did not highligh bugs while reading a xml string
The bug is fixed
**Other …
> Fix RoundTrip::run method

- extensions/entsoe/include/powsybl/iidm/extensions/entsoe/EntsoeAreaXmlSerializer.hpp
- extensions/entsoe/include/powsybl/iidm/extensions/entsoe/MergedXnodeXmlSerializer.hpp
- extensions/entsoe/include/powsybl/iidm/extensions/entsoe/XnodeXmlSerializer.hpp
- extensions/entsoe/src/EntsoeAreaXmlSerializer.cpp
- extensions/entsoe/src/MergedXnodeXmlSerializer.cpp
- extensions/entsoe/src/XnodeXmlSerializer.cpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/ActivePowerControlXmlSerializer.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/CoordinatedReactiveControlXmlSerializer.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/TwoWindingsTransformerPhaseAngleClockXmlSerializer.hpp
- extensions/iidm/src/ActivePowerControlXmlSerializer.cpp
- extensions/iidm/src/CoordinatedReactiveControlXmlSerializer.cpp
- extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClockXmlSerializer.cpp
- extensions/iidm/src/TwoWindingsTransformerPhaseAngleClockXmlSerializer.cpp
- include/powsybl/iidm/converter/xml/ExtensionXmlSerializer.hpp
- src/iidm/converter/xml/NetworkXml.cpp
- test/iidm/converter/xml/extensions/LoadBarXmlSerializer.cpp
- test/iidm/converter/xml/extensions/LoadBarXmlSerializer.hpp
- test/iidm/converter/xml/extensions/LoadFooXmlSerializer.cpp
- test/iidm/converter/xml/extensions/LoadFooXmlSerializer.hpp
- test/iidm/converter/xml/extensions/LoadMockExtXmlSerializer.cpp
- test/iidm/converter/xml/extensions/LoadMockExtXmlSerializer.hpp
- test/iidm/converter/xml/extensions/LoadQuxXmlSerializer.cpp
- test/iidm/converter/xml/extensions/LoadQuxXmlSerializer.hpp
- test/iidm/converter/xml/extensions/TerminalMockXmlSerializer.cpp
- test/iidm/converter/xml/extensions/TerminalMockXmlSerializer.hpp
No
Refactoring
While reading an extension from an XML, the extension is added after it was read (i.e that `ExtensionProvider::read` was called).
For extensions which have an adder, it is added twice by returning a copy (the second call to addExtension does nothing ; extensions are stores by name in the …
> Add the extension in read method and not by read caller

- examples/example1/example1.cpp
- include/powsybl/iidm/ExtensionProviders.hpp
- include/powsybl/logging/ConsoleLogger.hpp
- src/iidm/ExtensionProviders.cpp
- src/logging/ConsoleLogger.cpp
- test/logging/ConsoleLoggerTest.cpp
- test/logging/LoggerFactoryTest.cpp
- tools/benchmark/Benchmark.cpp
N/A
Bug fix
The iidm-benchmark tool crash when there are extensions in the XIIDM files. The shared_library are unloaded before used, so we have to store them in the ExtensionProviders singleton.
There is no crash anymore. We also add a new `ext-path` extension to set the path where the extensions …
> Fix ExtensionProvider

- include/powsybl/iidm/NetworkIndex.hpp
- include/powsybl/iidm/NetworkIndex.hxx
- src/iidm/NetworkIndex.cpp
- src/iidm/VoltageLevelAdder.cpp
- test/iidm/BusBreakerVoltageLevelTest.cpp
- test/iidm/NodeBreakerVoltageLevelTest.cpp
No (found while testing issue #125)
Bug fix
Removing a VoltageLevel from a network crashes because `NetworkIndex::m_objectsByType` contains 1 entry/key for every VoltageLevels in the Network. While removing a NodeBreakerVoltageLevel, the effective type is not found in the map => crash
Now, …
> Fix crash when removing a VoltageLevel

- tools/benchmark/Benchmark.cpp
N/A
Bug fix
The `ext-path` option's value is not well parsed, so it's not usable at all.
The ext-path option works properly …
> Fix ext-path parsing in iidm-benchmark tool

- .github/workflows/ci.yml
- .github/workflows/clang-tidy.yml
#173 
CI
The PR #178 doesn't work properly when multiple commits are in a PR.
We create a separate jobs for clang-tidy analysis that is triggered on push and on pull_request events. If the branch is not associated to a pull request, the job fail.
In the existing CI script, we merge the QA and Linux …
> Clang tidy

- .github/workflows/clang-tidy.yml
No
Bug fix
When executing clang-tidy from CI, the analysis is performed on every files, even the deleted ones, so that an error occurs.
Deleted files are excluded by using `--diff-filter=d` option to the `git diff` command line.
**Does this PR introduce a breaking change or deprecate an API?** *If …
> [IIDM v1.3] Exclude deleted files from clang-tidy analysis

- .clang-tidy
- include/powsybl/math/UndirectedGraph.hxx
- src/iidm/Connectable.cpp
- src/iidm/MergedBus.cpp
#201 
Bug fix
Compilation is not OK with gcc 10. Clang-tidy also reports errors.
Compilation is ok with g++ 10 (debian testing), clang++ 10 (ubuntu 20.04)
(if any of the …
> G++ clang 10

- include/powsybl/iidm/ThreeWindingsTransformer.hpp
- src/iidm/ThreeWindingsTransformer.cpp
- test/iidm/ThreeWindingsTransformerTest.cpp
N/A
Refactoring
The `getTerminal()` method of the 3WT legs return a `Reference<Terminal>` object instead of a `Terminal&` like other identifiables
The methods are consistent with the rest of the API …
> 3wt leg getterminal

- include/powsybl/iidm/NetworkIndex.hpp
- include/powsybl/iidm/NetworkIndex.hxx
- include/powsybl/stdcxx/instanceof.hpp
- src/iidm/Network.cpp
- src/iidm/NetworkIndex.cpp
- test/iidm/CMakeLists.txt
- test/iidm/NetworkExtension.cpp
- test/iidm/NetworkExtension.hpp
- test/iidm/NetworkIndexTest.cpp
- test/iidm/NetworkTest.cpp
N/A
Bug fix
Currently the network is not in the index. When a variant is created or removed, the network is not notified. If a multi-variant extension is attached to the network, the extension fields are not extended.
This PR insert the network in its own index. To do that, we need to customize the …
> Fix multi-variant implementation by adding the Network in the index

- include/powsybl/iidm/converter/ExportOptions.hpp
- include/powsybl/iidm/converter/xml/IidmXmlUtil.hpp
- src/iidm/converter/ExportOptions.cpp
- src/iidm/converter/xml/IidmXmlUtil.cpp
- src/iidm/converter/xml/StaticVarCompensatorXml.cpp
- src/iidm/converter/xml/ThreeWindingsTransformerXml.cpp
- src/iidm/converter/xml/VoltageLevelXml.cpp
- test/iidm/converter/ExportOptionsTest.cpp
- test/iidm/converter/xml/CMakeLists.txt
- test/iidm/converter/xml/IidmXmlUtilTest.cpp
Partial backport of Java PR https://github.com/powsybl/powsybl-core/pull/1535.
This PR reports the add of `ExportOptions::IidmVersionIncompatibilityBehavior` and updates `IidmXmlUtil` functions to consider the attribute value.
No
Developper wants to configure the behaviour (thrown exception / log error) when an IIDM version incompatibility occurs while reading/writing a network. This PR allows that feature.
**What is the current …
> [IIDM v1.3] Add Enum to change behaviour in case of IIDM version incompatibility

- include/powsybl/stdcxx/flattened.hpp
- src/iidm/BusBreakerVoltageLevel.cpp
- src/iidm/MergedBus.cpp
- src/iidm/NetworkViews.cpp
- src/iidm/Substation.cpp
#44 
Performance
The usage of `boost::range::join` in a for loop in not efficient and can lead to a memory crash (OOMKiller) as explained in boostorg/range#118.
A custom iterator has been implemented to flatten a range of ranges. The design is based on [this …
> Fix performance issue with boost::range::join

- src/iidm/HalfLine.cpp
No
Improvement
A HalfLine may be attached to a TieLine twice by a iidm4cpp developper mistake (from TieLine : halfLine::setParent is private, TieLine is friend)
Throw an error when trying to setParent twice
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the …
> Add check to ensure that HalfLine is not attached twice

- include/powsybl/iidm/ExtensionAdder.hpp
- include/powsybl/iidm/ShuntCompensatorLinearModelAdder.hpp
- include/powsybl/iidm/util/TerminalFinder.hpp
- include/powsybl/stdcxx/flattened.hpp
No
Compilation fix on CentOS 7
integration/v1.3.0 does not compile on CentOS7 operating system
integration/v1.3.0 compiles on CentOS7 operating system
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the …
> Fix compilation on CentOS 7

- .github/workflows/ci.yml
- src/iidm/converter/xml/ShuntCompensatorXml.cpp
- src/iidm/converter/xml/ShuntCompensatorXml.hpp
- test/iidm/converter/xml/CMakeLists.txt
- test/iidm/converter/xml/ShuntCompensatorRoundTripTest.cpp
- test/resources/V1_2/LccRoundTripRef.xml
- test/resources/V1_2/shuntRoundTripRef.xml
- test/resources/V1_2/terminalRef.xml
No
Bug fix
Shunt with regulation are not correctly written and read from XML : 
- <regulatingTerminal> is not emitted and read
- attribute "voltageRegulatorOn" is not written
- <regulatingTerminal> is written and read
- attribute …
> [IIDM v1.2] Fix XML read/write of shunts

- test/iidm/converter/xml/CMakeLists.txt
- test/iidm/converter/xml/HvdcRoundTripTest.cpp
- test/iidm/converter/xml/ShuntCompensatorRoundTripTest.cpp
No
Test refactoring
Shunt compensator round trip tests are in LccRoundTripRef.cpp (with LccRoundTrip test)
Vsc round trip test is in VscRoundTripTest.cpp
Shunt compensator round trip tests are in ShuntCompensatorRoundTripTest.cpp
Lcc and Vsc round trip tests are in HvdcRoundTripTest.cpp
**Does this …
> Fix Lcc/Vsc and shunts round trip tests

- tools/benchmark/Benchmark.cpp
- tools/benchmark/CMakeLists.txt
N/A
Feature
It's not possible to pass import/export options to `iidm-benchmark`
Options can be passed using the `-E` and `-I` options. Note that this is not totally equivalent to the java usage because we need to separate the prefix and the option name.
The tool is now install in the `bin` …
> Add a way to pass import/export options to iidm-benchmark

- include/powsybl/iidm/NetworkIndex.hpp
- include/powsybl/iidm/NetworkIndex.hxx
- src/iidm/NetworkIndex.cpp
- test/iidm/AliasesTest.cpp
No
Bug fix
`Network::find` does not consider aliases at all (unlike `Network::get`)
Network::find tries to resolve alias before searching in the id map
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check the …
> Add missing alias resolution when calling NetworkIndex::find()

- include/powsybl/iidm/DanglingLineGenerationAdder.hpp
- include/powsybl/iidm/HalfLine.hpp
- include/powsybl/iidm/Identifiable.hpp
- include/powsybl/iidm/NetworkVariant.hpp
- include/powsybl/iidm/ShuntCompensatorNonLinearModelAdder.hpp
- include/powsybl/iidm/Variant.hpp
- include/powsybl/stdcxx/flattened.hpp
- include/powsybl/stdcxx/map.hpp
- src/iidm/DanglingLineAdder.cpp
- src/iidm/Identifiable.cpp
- src/iidm/ShuntCompensatorNonLinearModel.cpp
- src/iidm/ShuntCompensatorNonLinearModelAdder.cpp
- src/iidm/TieLine.cpp
This PR fixes some smell based on the following report : https://sonarcloud.io/dashboard?id=com.powsybl%3Apowsybl-iidm4cpp&pullRequest=260
However, it does not fix the following smells :
Blockers:
- https://sonarcloud.io/project/issues?id=com.powsybl%3Apowsybl-iidm4cpp&open=AXbij5LuaZeqFyT-n8X8&pullRequest=260&resolved=false&severities=BLOCKER&types=CODE_SMELL
- https://sonarcloud.io/project/issues?id=com.powsybl%3Apowsybl-iidm4cpp&open=AXbij5TUaZeqFyT-n8Y2&pullRequest=260&resolved=false&severities=BLOCKER&types=CODE_SMELL
Critical:
- https://sonarcloud.io/project/issues?id=com.powsybl%3Apowsybl-iidm4cpp&open=AXbij5OuaZeqFyT-n8Ya&pullRequest=260&resolved=false&severities=CRITICAL&types=CODE_SMELL (when an HalfLine is moved, the line characteristic's validable attribute should be updated, …
> [IIDM v1.3] Fix some smells 

- include/powsybl/iidm/Identifiable.hpp
- include/powsybl/iidm/ShuntCompensatorNonLinearModelAdder.hpp
No
Fix regression introduced by PR https://github.com/powsybl/powsybl-iidm4cpp/pull/261 which makes compilation fail on Centos7
Does not compile on centos7 because of `noexcept` addition on `Identifiable(&&)` move constructor.
Does not compile on centos7
**Does this PR introduce a breaking change …
> Fix compilation on centos7

- examples/example1/example1.cpp
- include/powsybl/iidm/Identifiable.hpp
- include/powsybl/iidm/Network.hpp
- include/powsybl/test/ResourceFixture.hpp
- include/powsybl/test/converter/RoundTrip.hpp
- src/iidm/Network.cpp
- src/iidm/converter/xml/NetworkXml.cpp
- src/iidm/converter/xml/NetworkXml.hpp
- src/test/ResourceFixture.cpp
- src/test/converter/RoundTrip.cpp
- test/iidm/converter/xml/IdentifiableExtensionXmlSerializerTest.cpp
- test/iidm/converter/xml/LinesRoundTripTest.cpp
- test/iidm/converter/xml/NetworkXmlTest.cpp
- test/iidm/converter/xml/OptionalLoadTypeBugTest.cpp
- test/iidm/converter/xml/ShuntCompensatorRoundTripTest.cpp
- test/iidm/converter/xml/SkipExtensionTest.cpp
- test/iidm/extensions/LoadDetailTest.cpp
- tools/benchmark/Benchmark.cpp
No
XML serialization API update.
Update XML read/write API to prepare implementation of real anonymization (See PR #271) :
Functions available from public API of `Network` enabling to read/write do not pass filename which is needed so that CSV file can be guessed from input file like java Importers does.
**What is the new behavior (if this is a feature …
> Refactoring XML read/write of a Network API

- .github/workflows/ci.yml
- .github/workflows/clang-tidy.yml
No
Boost is not available on CI environments provided by github actions (https://github.com/actions/virtual-environments/issues/2667)
CI is failing because boost is required and not available on environments
Boost is installed : 
- From apt-get …
> Fix CI (boost not avaible on github actions)

- .github/workflows/ci.yml
- .github/workflows/clang-tidy.yml
No
Fix CI
CI is not OK because apt- repository is not up-to-date on ubuntu images
CI is OK.
(if any of the …
> Fix CI: invoke apt-get update before installing boost

- src/iidm/NodeBreakerVoltageLevel.cpp
- test/iidm/CMakeLists.txt
- test/iidm/NodeBreakerConnectTest.cpp
> Fix multiple connect/disconnect in NodeBreakerVoltageLevel (#285)

- src/iidm/converter/xml/TerminalRefXml.cpp
- test/iidm/NodeBreakerVoltageLevelTest.cpp
> Throw a comprehensive exception when a terminal ref of a busbar section on is written in bus-breaker or bus-branch (#295)

- src/iidm/NodeBreakerVoltageLevel.cpp
⚠️ target branch to be checked ⚠️ 
No
Bug fix
Synchronous and connected components is not invalidated when NBVL cache is invalidated
Synchronous and connected components is invalidated when NBVL cache is invalidated
**Does this PR introduce a breaking change or deprecate an API?** *If yes, check …
> Invalidate components managers when invalidate cache of NBVL

- src/iidm/MergedBus.cpp
- test/iidm/BusTest.cpp
⚠️ To be discussed : this issue was already OK in C++, I just added tests that where added in Java PR (https://github.com/powsybl/powsybl-core/pull/1647), but it may not be relevant...
#333 
**Does this PR introduce a breaking change or deprecate …
> Bug fix in MergedBus : getConnectedTerminalCount did not use the connected terminals but all (#333)

- include/powsybl/iidm/ValidationUtils.hpp
- src/iidm/ShuntCompensatorLinearModel.cpp
- src/iidm/ShuntCompensatorLinearModelAdder.cpp
- src/iidm/ShuntCompensatorNonLinearModelAdder.cpp
- src/iidm/ValidationUtils.cpp
- test/iidm/ShuntCompensatorTest.cpp
> Allow bPerSection to be equals to zero in ShuntCompensator linear model (#336)

- src/iidm/converter/xml/TerminalRefXml.cpp
- test/iidm/converter/xml/TerminalRefTest.cpp
- test/resources/V1_5/terminalRefNotFound.xml
In C++, the old error was :
```
"Unable to find to the identifiable '????'"
```
It is now the same as in java : 
```
Terminal reference identifiable not found: '????'
```
Closes #338
**Does this PR introduce a breaking change or deprecate an …
> Improve error message while reading terminal ref with invalid identifiable (#338)

- extensions/entsoe/test/EntsoeAreaTest.cpp
- src/iidm/Extendable.cpp
⚠️ Target branch to be checked
No
Bug fix
When 2 extensions of the same type are added to an Extendable, the extension of the given type always remain the first added.
Reproduction case:
```
Network network("test", "test");
network.setCaseDate(stdcxx::DateTime::parse("2016-06-27T12:27:58.535+02:00")); …
```
> Fix multiple extension add

- extensions/entsoe/include/powsybl/iidm/extensions/entsoe/EntsoeArea.hpp
- extensions/entsoe/include/powsybl/iidm/extensions/entsoe/MergedXnode.hpp
- extensions/entsoe/include/powsybl/iidm/extensions/entsoe/Xnode.hpp
- extensions/entsoe/src/EntsoeAreaAdder.cpp
- extensions/entsoe/src/MergedXnodeAdder.cpp
- extensions/entsoe/src/XnodeAdder.cpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/ActivePowerControl.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/CoordinatedReactiveControl.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/HvdcAngleDroopActivePowerControl.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/HvdcOperatorActivePowerRange.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/ThreeWindingsTransformerPhaseAngleClock.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/TwoWindingsTransformerPhaseAngleClock.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/VoltagePerReactivePowerControl.hpp
- extensions/iidm/src/ActivePowerControlAdder.cpp
- extensions/iidm/src/CoordinatedReactiveControlAdder.cpp
- extensions/iidm/src/HvdcAngleDroopActivePowerControlAdder.cpp
- extensions/iidm/src/HvdcOperatorActivePowerRangeAdder.cpp
- extensions/iidm/src/ThreeWindingsTransformerPhaseAngleClockAdder.cpp
- extensions/iidm/src/TwoWindingsTransformerPhaseAngleClockAdder.cpp
- extensions/iidm/src/VoltagePerReactivePowerControlAdder.cpp
- extensions/sld/include/powsybl/iidm/extensions/sld/BusbarSectionPosition.hpp
- extensions/sld/include/powsybl/iidm/extensions/sld/ConnectablePosition.hpp
- extensions/sld/src/BusbarSectionPositionAdder.cpp
- extensions/sld/src/ConnectablePositionAdder.cpp
No
In PR #355, the extension constructors are now private so that user can only add them by using the extension adder. To be able to call it, we decided to make `stdcxx::make_unique` friend of the extensions classes. But it is not possible to restrict friendship for templated methods, so the generic stdcxx::make_unique method can call constructors.. So the PR !355 does not fix …
> Fix friendship handling for private extension contructor

- extensions/sld/test/ConnectablePositionTest.cpp
No
Removal of a std::cout usage in sld tests
> Removed useless std::cout in test

- include/powsybl/iidm/VoltageLevelViews.hpp
- src/iidm/NodeBreakerVoltageLevel.cpp
- src/iidm/NodeBreakerVoltageLevel.hpp
- src/iidm/NodeBreakerVoltageLevelViews.cpp
- src/iidm/NodeBreakerVoltageLevelViews.hpp
- test/iidm/NodeBreakerVoltageLevelTest.cpp
> Fix NodeBreakerVoltageLevel::getMaximumNodeIndex() (#398)

- include/powsybl/stdcxx/reference.hpp
- test/stdcxx/CMakeLists.txt
- test/stdcxx/ReferenceTest.cpp
No
Bug fix
The library crashes by writing such code:
```
std::unique_ptr<int> ptr;
auto ref = stdcxx::ref<int>(ptr);  // crash here
```
The library does not crashes, the code snippet returns an invalid `stdcxx::Reference`
**Does this PR introduce a breaking change or deprecate an API?** *If yes, …
> Fix stdcxx::ref(std::unique_ptr) and stdcxx::cref(std::unique_ptr)

- include/powsybl/iidm/ActivePowerLimits.hpp
- include/powsybl/iidm/ActivePowerLimitsAdder.hpp
- include/powsybl/iidm/ApparentPowerLimits.hpp
- include/powsybl/iidm/ApparentPowerLimitsAdder.hpp
- include/powsybl/iidm/CurrentLimits.hpp
- include/powsybl/iidm/CurrentLimitsAdder.hpp
- include/powsybl/iidm/LoadingLimits.hpp
- include/powsybl/iidm/LoadingLimitsAdder.hpp
- include/powsybl/iidm/LoadingLimitsAdder.hxx
- include/powsybl/iidm/OperationalLimits.hpp
- include/powsybl/iidm/OperationalLimitsHolder.hpp
- include/powsybl/iidm/OperationalLimitsHolder.hxx
- include/powsybl/iidm/OperationalLimitsOwner.hpp
- src/iidm/ActivePowerLimits.cpp
- src/iidm/ActivePowerLimitsAdder.cpp
- src/iidm/ApparentPowerLimits.cpp
- src/iidm/ApparentPowerLimitsAdder.cpp
- src/iidm/CurrentLimits.cpp
- src/iidm/CurrentLimitsAdder.cpp
- src/iidm/LoadingLimits.cpp
- src/iidm/OperationalLimits.cpp
- src/iidm/OperationalLimitsHolder.cpp
No
Add `OperationalLimitsOwner` interface which is inherited by concrete `OperationalLimitsHolder`. This interface may be needed to avoir using `OperationalLimitsHolder` which enabled to store every kind of `OperationalLimits`
Both Java classes `OperationalLimitsOwner` and `OperationalLimitsHolder` are …
> Add OperationalLimitsOwner

- include/powsybl/stdcxx/cast.hpp
- src/iidm/BusBreakerVoltageLevelViews.cpp
- src/iidm/CalculatedBus.cpp
- src/iidm/ConfiguredBus.cpp
- src/iidm/NodeBreakerVoltageLevelViews.cpp
- test/stdcxx/CMakeLists.txt
- test/stdcxx/CastTest.cpp
No
Feature
In order to cast a `std::unique_ptr<Base>` into a `std::unique_ptr<Derived>` the ownership of data has to be updated. I added some user-friendly methods in order to do that more easily.
It is possible to downcast/upcast std::unique_ptr …
> Add casts utilities for std::unique_ptr

- src/iidm/BusBreakerVoltageLevel.cpp
- src/iidm/MultipleVariantContext.cpp
⚠️ Target branch to be defined ⚠️ 
No
Bug fix (fix compilation with C++-17 compliant compilers)
With C++-17 and newer versions, `stdcxx::optional` = `std::optional`. With older compilers, `stdcxx::optional` = `boost::optional`.
Sometimes, we called `stdcxx::optional::get()` which is boost-specific => the library does not compile with recents compilers. …
> Fix usage of stdcxx::optional with C++-17 compliant compilers

- include/powsybl/iidm/BusCache.hpp
- include/powsybl/stdcxx/flattened.hpp
N/A
Compilation issue
Under CentOS 7, with Clang, the build fails
With these two fixes, the build works properly
(if any of the questions/checkboxes don't apply, please delete …
> Fix compilation under CentOS 7 and Clang

- test/iidm/CMakeLists.txt
- test/iidm/util/SVTest.cpp
No
Add tests/iidm in include path, because it contains `NetworkFactory.hpp`, which contains useful network for tests, but the file could not be included simply
NetworkFactory.hpp can be included by writing
```
#include "../NetworkFactory.hpp"
``` …
> Add iidm test directory in include path 

- extensions/iidm/CMakeLists.txt
- extensions/iidm/include/powsybl/iidm/extensions/iidm/GeneratorShortCircuit.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/GeneratorShortCircuitAdder.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/IdentifiableShortCircuit.hpp
- extensions/iidm/include/powsybl/iidm/extensions/iidm/IdentifiableShortCircuitAdder.hpp
- extensions/iidm/src/GeneratorShortCircuit.cpp
- extensions/iidm/src/GeneratorShortCircuitAdder.cpp
- extensions/iidm/src/IdentifiableShortCircuit.cpp
- extensions/iidm/src/IdentifiableShortCircuitAdder.cpp
- extensions/iidm/test/GeneratorShortCircuitTest.cpp
- extensions/iidm/test/IdentifiableShortCircuitTest.cpp
Closes #384 
Closes #419 (https://github.com/powsybl/powsybl-core/pull/1925)
> Add shortcircuit extensions (#384)

- .clang-tidy
- .github/workflows/clang-tidy.yml
No
CI fix
Clang-tidy 9 is not available anymore on ubuntu 22.04 => CI is broken
Use clang-tidy-14, so that CI is ok
No …
> Udpate clang tidy

- src/xml/XmlStreamWriter.cpp
No
Bug fix
XML unparsing in a file duplicates the network under Windows. It's ok under linux.
XML unparsing is ok on Windows (and linux also)
No
(if any of the …
> Fix XML unparsing under windows

- src/xml/XmlStreamWriter.cpp
No
Bug Fix
Unparsing on a file on Windows does not work properly : <network> tag is duplicated. This can be reproduced by launching 
```
$ iidm-benchmark.exe --input-file  test\resources\V1_4\fourSubstationsNbk.xml --output-file out.txt
```
out.txt is the following : …
> Fix write callback of XmlStreamWriter which did not work properly on Windows
